# Generated by Django 5.1.1 on 2026-08-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slots', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompletionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('floors', models.JSONField(default=dict)),
                ('total_cost', models.IntegerField(default=0)),
                ('sg_cost', models.IntegerField(default=0)),
                ('reward_counts', models.JSONField(default=dict)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.JSONField(default=list)),
                ('sg_table', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'game meta',
            },
        ),
    ]
